["moe.kawayi.org.utopia.generated.plugin_info.name"]
provider = "moe.kawayi.org.utopia.generated.translate.provider"
comment = "the translation of the name"
translated = ""
["moe.kawayi.org.utopia.generated.plugin_info.description"]
provider = "moe.kawayi.org.utopia.generated.translate.provider"
comment = "the translation of the description"
translated = ""
