using System.Text;

namespace Utopia.Tools.Generators;

public class CsBuilder
{

    public List<string> Usings = new();

    public string? Namespace = null;

    public List<string> Lines = new();

    public void AddClass(string className, bool isPublic = false, bool isStatic = false, params string[] parentClass)
    {
        var pub = isPublic ? "public" : string.Empty;
        var sat = isStatic ? "static" : string.Empty;

        var parent = parentClass.Length == 0 ? string.Empty : " : ";
        foreach (var c in parentClass)
        {
            parent += $"{c},";
        }
        if (parentClass.Length != 0)
        {
            parent = parent[0..^1];
        }

        this.Lines.Add($"{pub} {sat} class {className} {parent} {{");
    }

    public string Generate()
    {
        StringBuilder sb = new();

        sb.AppendLine("// This file was generated by source generator.");

        foreach (var s in this.Usings)
        {
            sb.Append("using ").Append(s).AppendLine(";");
        }

        if (this.Namespace != null)
        {
            sb.AppendLine($"namespace {this.Namespace};");
        }

        foreach (var s in this.Lines)
        {
            sb.AppendLine(s);
        }

        return sb.ToString();
    }

}
