# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build-And-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            version: ['8.0.x']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: 'latest'
    - name: Setup Nuke
      run: dotnet tool install Nuke.GlobalTool --global
    - name: Restore
      run: |
        dotnet restore
        nuke Restore
    - name: Build
      run: nuke CompileAll
    - name: Test
      run: nuke UnitTest
